/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const appCache: typeof import('../utils/cache').appCache
  const appEnv: typeof import('../utils/env').appEnv
  const chunk: typeof import('../utils/poly').chunk
  const compact: typeof import('../utils/poly').compact
  const componentGroups: typeof import('../utils/wotComponents').componentGroups
  const componentList: typeof import('../utils/wotComponents').componentList
  const composeValidators: typeof import('../utils/validate').composeValidators
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createCache: typeof import('../utils/cache').createCache
  const createPinia: typeof import('pinia').createPinia
  const createRequest: typeof import('../hooks/requests').createRequest
  const createValidateResult: typeof import('../utils/validate').createValidateResult
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const exampleScenarios: typeof import('../utils/exampleScenarios').exampleScenarios
  const feedCategories: typeof import('../utils/waterfallFeeds').feedCategories
  const findComponent: typeof import('../utils/wotComponents').findComponent
  const flatten: typeof import('../utils/poly').flatten
  const formatAddress: typeof import('../utils/format').formatAddress
  const formatBankCard: typeof import('../utils/format').formatBankCard
  const formatBoolean: typeof import('../utils/format').formatBoolean
  const formatCompactNumber: typeof import('../utils/format').formatCompactNumber
  const formatCount: typeof import('../utils/waterfallFeeds').formatCount
  const formatCountdown: typeof import('../utils/format').formatCountdown
  const formatCurrency: typeof import('../utils/format').formatCurrency
  const formatDate: typeof import('../utils/format').formatDate
  const formatDateRange: typeof import('../utils/format').formatDateRange
  const formatDateTime: typeof import('../utils/format').formatDateTime
  const formatDuration: typeof import('../utils/format').formatDuration
  const formatEmpty: typeof import('../utils/format').formatEmpty
  const formatFileSize: typeof import('../utils/format').formatFileSize
  const formatListText: typeof import('../utils/format').formatListText
  const formatNumber: typeof import('../utils/format').formatNumber
  const formatPercent: typeof import('../utils/format').formatPercent
  const formatQuery: typeof import('../utils/format').formatQuery
  const formatRelativeTime: typeof import('../utils/format').formatRelativeTime
  const formatSignedNumber: typeof import('../utils/format').formatSignedNumber
  const formatTime: typeof import('../utils/format').formatTime
  const formatWeekday: typeof import('../utils/format').formatWeekday
  const getActivePinia: typeof import('pinia').getActivePinia
  const getActiveTabName: typeof import('../utils/tabbar').getActiveTabName
  const getComponentApi: typeof import('../utils/wotComponents').getComponentApi
  const getComponentCode: typeof import('../utils/wotComponents').getComponentCode
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getFeedsByScene: typeof import('../utils/waterfallFeeds').getFeedsByScene
  const getPlatformInfo: typeof import('../utils/platform').getPlatformInfo
  const getSpecialLength: typeof import('../utils/format').getSpecialLength
  const getWaterfallFeed: typeof import('../utils/waterfallFeeds').getWaterfallFeed
  const groupBy: typeof import('../utils/poly').groupBy
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isBankCard: typeof import('../utils/validate').isBankCard
  const isChineseName: typeof import('../utils/validate').isChineseName
  const isEmail: typeof import('../utils/validate').isEmail
  const isEmpty: typeof import('../utils/validate').isEmpty
  const isIdCard: typeof import('../utils/validate').isIdCard
  const isNumberLike: typeof import('../utils/validate').isNumberLike
  const isPhone: typeof import('../utils/validate').isPhone
  const isPlateNumber: typeof import('../utils/validate').isPlateNumber
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isStrongPassword: typeof import('../utils/validate').isStrongPassword
  const isUrl: typeof import('../utils/validate').isUrl
  const lifeFeeds: typeof import('../utils/waterfallFeeds').lifeFeeds
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const maskBankCard: typeof import('../utils/format').maskBankCard
  const maskIdCard: typeof import('../utils/format').maskIdCard
  const maskPhone: typeof import('../utils/format').maskPhone
  const maskText: typeof import('../utils/format').maskText
  const maxLength: typeof import('../utils/validate').maxLength
  const minLength: typeof import('../utils/validate').minLength
  const momentFeeds: typeof import('../utils/waterfallFeeds').momentFeeds
  const navigateBack: typeof import('../utils/router').navigateBack
  const navigateTo: typeof import('../utils/router').navigateTo
  const navigateToExample: typeof import('../utils/exampleScenarios').navigateToExample
  const newsFeeds: typeof import('../utils/waterfallFeeds').newsFeeds
  const nextTick: typeof import('vue').nextTick
  const numberToChinese: typeof import('../utils/format').numberToChinese
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onHide: typeof import('@dcloudio/uni-app').onHide
  const onLaunch: typeof import('@dcloudio/uni-app').onLaunch
  const onLoad: typeof import('@dcloudio/uni-app').onLoad
  const onMounted: typeof import('vue').onMounted
  const onPageScroll: typeof import('@dcloudio/uni-app').onPageScroll
  const onPullDownRefresh: typeof import('@dcloudio/uni-app').onPullDownRefresh
  const onReachBottom: typeof import('@dcloudio/uni-app').onReachBottom
  const onReady: typeof import('@dcloudio/uni-app').onReady
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onShareAppMessage: typeof import('@dcloudio/uni-app').onShareAppMessage
  const onShow: typeof import('@dcloudio/uni-app').onShow
  const onUnload: typeof import('@dcloudio/uni-app').onUnload
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseQuery: typeof import('../utils/format').parseQuery
  const pattern: typeof import('../utils/validate').pattern
  const provide: typeof import('vue').provide
  const range: typeof import('../utils/poly').range
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const redirectTo: typeof import('../utils/router').redirectTo
  const ref: typeof import('vue').ref
  const request: typeof import('../hooks/requests').request
  const required: typeof import('../utils/validate').required
  const resolveComponent: typeof import('vue').resolveComponent
  const safeRun: typeof import('../utils/poly').safeRun
  const sceneTabs: typeof import('../utils/waterfallFeeds').sceneTabs
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const shopFeeds: typeof import('../utils/waterfallFeeds').shopFeeds
  const slugify: typeof import('../utils/poly').slugify
  const storeToRefs: typeof import('pinia').storeToRefs
  const switchTabByName: typeof import('../utils/tabbar').switchTabByName
  const tabbarItems: typeof import('../utils/tabbar').tabbarItems
  const titleCase: typeof import('../utils/poly').titleCase
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const truncateBySpecialLength: typeof import('../utils/format').truncateBySpecialLength
  const uniqBy: typeof import('../utils/poly').uniqBy
  const unref: typeof import('vue').unref
  const useAppEnv: typeof import('../hooks/useAppEnv').useAppEnv
  const useAppStore: typeof import('../store/app').useAppStore
  const useAttrs: typeof import('vue').useAttrs
  const useBackRefresh: typeof import('../hooks/useBackRefresh').useBackRefresh
  const useConfigProvider: typeof import('wot-design-uni').useConfigProvider
  const useCountDown: typeof import('wot-design-uni').useCountDown
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useI18n: typeof import('../hooks/useI18n').useI18n
  const useId: typeof import('vue').useId
  const useMessage: typeof import('wot-design-uni').useMessage
  const useModel: typeof import('vue').useModel
  const useNotify: typeof import('wot-design-uni').useNotify
  const usePagePagination: typeof import('../hooks/pagination').usePagePagination
  const usePlatform: typeof import('../hooks/usePlatform').usePlatform
  const useSlots: typeof import('vue').useSlots
  const useStepPagination: typeof import('../hooks/pagination').useStepPagination
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useToast: typeof import('wot-design-uni').useToast
  const useUpload: typeof import('wot-design-uni').useUpload
  const useUserStore: typeof import('../store/user').useUserStore
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const waterfallFeeds: typeof import('../utils/waterfallFeeds').waterfallFeeds
  const zip: typeof import('../utils/poly').zip
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { PagePaginationOptions, StepPaginationOptions } from '../hooks/pagination'
  import('../hooks/pagination')
  // @ts-ignore
  export type { RequestMethod, RequestOptions, RequestConfig } from '../hooks/requests'
  import('../hooks/requests')
  // @ts-ignore
  export type { BackRefreshPayload, NavigateBackOptions } from '../hooks/useBackRefresh'
  import('../hooks/useBackRefresh')
  // @ts-ignore
  export type { UserProfile } from '../store/user'
  import('../store/user')
  // @ts-ignore
  export type { CachePayload, CacheOptions } from '../utils/cache'
  import('../utils/cache')
  // @ts-ignore
  export type { AppEnvMode } from '../utils/env'
  import('../utils/env')
  // @ts-ignore
  export type { ExampleScenario } from '../utils/exampleScenarios'
  import('../utils/exampleScenarios')
  // @ts-ignore
  export type { DateInput, VisualLengthOptions } from '../utils/format'
  import('../utils/format')
  // @ts-ignore
  export type { PlatformTarget, PlatformInfo } from '../utils/platform'
  import('../utils/platform')
  // @ts-ignore
  export type { SafeRunResult } from '../utils/poly'
  import('../utils/poly')
  // @ts-ignore
  export type { TabbarName, TabbarItem } from '../utils/tabbar'
  import('../utils/tabbar')
  // @ts-ignore
  export type { ValidateResult, Validator } from '../utils/validate'
  import('../utils/validate')
  // @ts-ignore
  export type { WaterfallScene, WaterfallFeed } from '../utils/waterfallFeeds'
  import('../utils/waterfallFeeds')
  // @ts-ignore
  export type { ComponentItem, ComponentGroup, ApiRow } from '../utils/wotComponents'
  import('../utils/wotComponents')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly appCache: UnwrapRef<typeof import('../utils/cache')['appCache']>
    readonly appEnv: UnwrapRef<typeof import('../utils/env')['appEnv']>
    readonly chunk: UnwrapRef<typeof import('../utils/poly')['chunk']>
    readonly compact: UnwrapRef<typeof import('../utils/poly')['compact']>
    readonly componentGroups: UnwrapRef<typeof import('../utils/wotComponents')['componentGroups']>
    readonly componentList: UnwrapRef<typeof import('../utils/wotComponents')['componentList']>
    readonly composeValidators: UnwrapRef<typeof import('../utils/validate')['composeValidators']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createCache: UnwrapRef<typeof import('../utils/cache')['createCache']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly createRequest: UnwrapRef<typeof import('../hooks/requests')['createRequest']>
    readonly createValidateResult: UnwrapRef<typeof import('../utils/validate')['createValidateResult']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly exampleScenarios: UnwrapRef<typeof import('../utils/exampleScenarios')['exampleScenarios']>
    readonly feedCategories: UnwrapRef<typeof import('../utils/waterfallFeeds')['feedCategories']>
    readonly findComponent: UnwrapRef<typeof import('../utils/wotComponents')['findComponent']>
    readonly flatten: UnwrapRef<typeof import('../utils/poly')['flatten']>
    readonly formatAddress: UnwrapRef<typeof import('../utils/format')['formatAddress']>
    readonly formatBankCard: UnwrapRef<typeof import('../utils/format')['formatBankCard']>
    readonly formatBoolean: UnwrapRef<typeof import('../utils/format')['formatBoolean']>
    readonly formatCompactNumber: UnwrapRef<typeof import('../utils/format')['formatCompactNumber']>
    readonly formatCount: UnwrapRef<typeof import('../utils/waterfallFeeds')['formatCount']>
    readonly formatCountdown: UnwrapRef<typeof import('../utils/format')['formatCountdown']>
    readonly formatCurrency: UnwrapRef<typeof import('../utils/format')['formatCurrency']>
    readonly formatDate: UnwrapRef<typeof import('../utils/format')['formatDate']>
    readonly formatDateRange: UnwrapRef<typeof import('../utils/format')['formatDateRange']>
    readonly formatDateTime: UnwrapRef<typeof import('../utils/format')['formatDateTime']>
    readonly formatDuration: UnwrapRef<typeof import('../utils/format')['formatDuration']>
    readonly formatEmpty: UnwrapRef<typeof import('../utils/format')['formatEmpty']>
    readonly formatFileSize: UnwrapRef<typeof import('../utils/format')['formatFileSize']>
    readonly formatListText: UnwrapRef<typeof import('../utils/format')['formatListText']>
    readonly formatNumber: UnwrapRef<typeof import('../utils/format')['formatNumber']>
    readonly formatPercent: UnwrapRef<typeof import('../utils/format')['formatPercent']>
    readonly formatQuery: UnwrapRef<typeof import('../utils/format')['formatQuery']>
    readonly formatRelativeTime: UnwrapRef<typeof import('../utils/format')['formatRelativeTime']>
    readonly formatSignedNumber: UnwrapRef<typeof import('../utils/format')['formatSignedNumber']>
    readonly formatTime: UnwrapRef<typeof import('../utils/format')['formatTime']>
    readonly formatWeekday: UnwrapRef<typeof import('../utils/format')['formatWeekday']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getActiveTabName: UnwrapRef<typeof import('../utils/tabbar')['getActiveTabName']>
    readonly getComponentApi: UnwrapRef<typeof import('../utils/wotComponents')['getComponentApi']>
    readonly getComponentCode: UnwrapRef<typeof import('../utils/wotComponents')['getComponentCode']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getFeedsByScene: UnwrapRef<typeof import('../utils/waterfallFeeds')['getFeedsByScene']>
    readonly getPlatformInfo: UnwrapRef<typeof import('../utils/platform')['getPlatformInfo']>
    readonly getSpecialLength: UnwrapRef<typeof import('../utils/format')['getSpecialLength']>
    readonly getWaterfallFeed: UnwrapRef<typeof import('../utils/waterfallFeeds')['getWaterfallFeed']>
    readonly groupBy: UnwrapRef<typeof import('../utils/poly')['groupBy']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isBankCard: UnwrapRef<typeof import('../utils/validate')['isBankCard']>
    readonly isChineseName: UnwrapRef<typeof import('../utils/validate')['isChineseName']>
    readonly isEmail: UnwrapRef<typeof import('../utils/validate')['isEmail']>
    readonly isEmpty: UnwrapRef<typeof import('../utils/validate')['isEmpty']>
    readonly isIdCard: UnwrapRef<typeof import('../utils/validate')['isIdCard']>
    readonly isNumberLike: UnwrapRef<typeof import('../utils/validate')['isNumberLike']>
    readonly isPhone: UnwrapRef<typeof import('../utils/validate')['isPhone']>
    readonly isPlateNumber: UnwrapRef<typeof import('../utils/validate')['isPlateNumber']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isStrongPassword: UnwrapRef<typeof import('../utils/validate')['isStrongPassword']>
    readonly isUrl: UnwrapRef<typeof import('../utils/validate')['isUrl']>
    readonly lifeFeeds: UnwrapRef<typeof import('../utils/waterfallFeeds')['lifeFeeds']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly maskBankCard: UnwrapRef<typeof import('../utils/format')['maskBankCard']>
    readonly maskIdCard: UnwrapRef<typeof import('../utils/format')['maskIdCard']>
    readonly maskPhone: UnwrapRef<typeof import('../utils/format')['maskPhone']>
    readonly maskText: UnwrapRef<typeof import('../utils/format')['maskText']>
    readonly maxLength: UnwrapRef<typeof import('../utils/validate')['maxLength']>
    readonly minLength: UnwrapRef<typeof import('../utils/validate')['minLength']>
    readonly momentFeeds: UnwrapRef<typeof import('../utils/waterfallFeeds')['momentFeeds']>
    readonly navigateBack: UnwrapRef<typeof import('../utils/router')['navigateBack']>
    readonly navigateTo: UnwrapRef<typeof import('../utils/router')['navigateTo']>
    readonly navigateToExample: UnwrapRef<typeof import('../utils/exampleScenarios')['navigateToExample']>
    readonly newsFeeds: UnwrapRef<typeof import('../utils/waterfallFeeds')['newsFeeds']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly numberToChinese: UnwrapRef<typeof import('../utils/format')['numberToChinese']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onHide: UnwrapRef<typeof import('@dcloudio/uni-app')['onHide']>
    readonly onLaunch: UnwrapRef<typeof import('@dcloudio/uni-app')['onLaunch']>
    readonly onLoad: UnwrapRef<typeof import('@dcloudio/uni-app')['onLoad']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onPageScroll: UnwrapRef<typeof import('@dcloudio/uni-app')['onPageScroll']>
    readonly onPullDownRefresh: UnwrapRef<typeof import('@dcloudio/uni-app')['onPullDownRefresh']>
    readonly onReachBottom: UnwrapRef<typeof import('@dcloudio/uni-app')['onReachBottom']>
    readonly onReady: UnwrapRef<typeof import('@dcloudio/uni-app')['onReady']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onShareAppMessage: UnwrapRef<typeof import('@dcloudio/uni-app')['onShareAppMessage']>
    readonly onShow: UnwrapRef<typeof import('@dcloudio/uni-app')['onShow']>
    readonly onUnload: UnwrapRef<typeof import('@dcloudio/uni-app')['onUnload']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly parseQuery: UnwrapRef<typeof import('../utils/format')['parseQuery']>
    readonly pattern: UnwrapRef<typeof import('../utils/validate')['pattern']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly range: UnwrapRef<typeof import('../utils/poly')['range']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly redirectTo: UnwrapRef<typeof import('../utils/router')['redirectTo']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly request: UnwrapRef<typeof import('../hooks/requests')['request']>
    readonly required: UnwrapRef<typeof import('../utils/validate')['required']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly safeRun: UnwrapRef<typeof import('../utils/poly')['safeRun']>
    readonly sceneTabs: UnwrapRef<typeof import('../utils/waterfallFeeds')['sceneTabs']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly shopFeeds: UnwrapRef<typeof import('../utils/waterfallFeeds')['shopFeeds']>
    readonly slugify: UnwrapRef<typeof import('../utils/poly')['slugify']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly switchTabByName: UnwrapRef<typeof import('../utils/tabbar')['switchTabByName']>
    readonly tabbarItems: UnwrapRef<typeof import('../utils/tabbar')['tabbarItems']>
    readonly titleCase: UnwrapRef<typeof import('../utils/poly')['titleCase']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly truncateBySpecialLength: UnwrapRef<typeof import('../utils/format')['truncateBySpecialLength']>
    readonly uniqBy: UnwrapRef<typeof import('../utils/poly')['uniqBy']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAppEnv: UnwrapRef<typeof import('../hooks/useAppEnv')['useAppEnv']>
    readonly useAppStore: UnwrapRef<typeof import('../store/app')['useAppStore']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useBackRefresh: UnwrapRef<typeof import('../hooks/useBackRefresh')['useBackRefresh']>
    readonly useConfigProvider: UnwrapRef<typeof import('wot-design-uni')['useConfigProvider']>
    readonly useCountDown: UnwrapRef<typeof import('wot-design-uni')['useCountDown']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useI18n: UnwrapRef<typeof import('../hooks/useI18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useMessage: UnwrapRef<typeof import('wot-design-uni')['useMessage']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNotify: UnwrapRef<typeof import('wot-design-uni')['useNotify']>
    readonly usePagePagination: UnwrapRef<typeof import('../hooks/pagination')['usePagePagination']>
    readonly usePlatform: UnwrapRef<typeof import('../hooks/usePlatform')['usePlatform']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useStepPagination: UnwrapRef<typeof import('../hooks/pagination')['useStepPagination']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToast: UnwrapRef<typeof import('wot-design-uni')['useToast']>
    readonly useUpload: UnwrapRef<typeof import('wot-design-uni')['useUpload']>
    readonly useUserStore: UnwrapRef<typeof import('../store/user')['useUserStore']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly waterfallFeeds: UnwrapRef<typeof import('../utils/waterfallFeeds')['waterfallFeeds']>
    readonly zip: UnwrapRef<typeof import('../utils/poly')['zip']>
  }
}